lines = [
  "object create(\"title\")",
  "{",
  "type \"text\"",
  "input \"Joyza OS\"",
  "scale 200",
  "}",
  "object create(\"bottom\")",
  "{",
  "type \"text\"",
  "input \"Dynamic Rendering\"",
  "rotation 90",
  "color #ff0",
  "pos 0,-25",
  "scale 90",
  "}"
]

objects = {}
object_create = false

object_pos = ""
object_scale = ""
object_input = ""
object_type = ""
object_rotation = ""
object_stretch = ""

compiled = []
append = []
parser = "/[()]/gmi"
count = 0
loop lines.len (
  count ++
  cur = lines.[count].str
  cur_spl = cur.split(" ")
  cur_repl = cur.replace(parser," ")
  cur_repl_spl = cur_repl.split(" ")
  out = ""
  out2 = ""
  if object_create.not (
    if cur_repl_spl.[1] == "object" (
      if cur_repl_spl.[2] == "create" (
        objects.key(count) = cur_repl_spl.[3]
        object_create = true
      )
    )
    if cur_repl_spl.[1] == "var" (
      if cur_repl_spl.[2] == "create" (
        if cur_repl_spl.[3].contains("|") (
          temp_sys = cur_repl_spl.[3].split("|")
          out = temp_sys.[1] + "=" + temp_sys.[2]
        ) else (
          out = cur_repl_spl.[3] + "= null"
        )
      )
      if cur_repl_spl.[2] == "delete" (
        out = cur_repl_spl.[3] + "= null"
      )
    )
    if cur_repl_spl.[1] == "print" (
      temp_sys = "log" + "sys".toStr().str
      out = cur_repl.replace("print",temp_sys)
      len = out.len - 1
      out = out.left(len)
    )
    if cur_spl.[2].contains("=") and ( cur_spl.[2].len < 3 ) (
      out = cur.str
    )
    if cur.left(3) == "if(" (
      out = cur_repl ++ "("
    )
    if cur.left(7) == "repeat(" (
      out = "loop" + cur_repl_spl.[2] + "("
    )
  )
  if object_create (
    log "sys" cur_repl_spl.[1]
    if cur_repl_spl.[1] == "type" (
      object_type = cur_repl_spl.[2]
    )
    if cur_repl_spl.[1] == "input" (
      object_input = cur_spl - 1
    )
    if cur_repl_spl.[1] == "scale" (
      object_scale = cur_repl_spl.[2]
    )
    if cur_repl_spl.[1] == "pos" (
      object_pos = cur_repl_spl.[2]
    )
    if cur_repl_spl.[1] == "rotation" (
      object_rotation = cur_repl_spl.[2]
    )
    if cur_repl_spl.[1] == "stretch" (
      object_stretch = cur_repl_spl.[2]
    )
  )
  if cur == "}" (
    if object_create.not (
      out = ")"
    )
    if object_create (
      object_create = false

      if object_input != "" (
        var_input = "object_input" ++ count
        append = append + ( var_input ++ " = " ++ object_input.join(" ") )
      )
      if object_pos != "" (
        var_pos = "object_pos" ++ count
        append = append + ( var_pos ++ " = " ++ object_pos.split(",") )
        compiled = compiled + ( "goto" + var_pos )
      )
      if object_rotation != "" (
        var_rotation = "object_rotaion" ++ count
        append = append + ( var_rotation ++ " = " ++ object_rotation )
        compiled = compiled + ( "direction" + var_rotation )
      )
      if object_stretch != "" (
        var_stretch = "object_stretch" ++ count
        append = append + ( var_stretch ++ " = " ++ object_stretch )
        compiled = compiled + ( "stretch" + var_stretch )
      )

      if object_type == "text" (
        out2 = "text <var_input> <object_scale>"
      )
      if object_type == "image" (
        out2 = "image " ++ var_input.destr + 100
      )

      object_pos = ""
      object_scale = ""
      object_input = ""
      object_type = ""
      object_rotation = ""
      object_stretch = ""
    )
  )
  if cur != "{" and object_create.not (
    if out != "" (
      compiled = compiled + out
    )
    if out2 != "" (
      compiled = compiled + out2
    )
  )
)
compiled = append + "mainloop:" ++ compiled
out = null
count = 0
loop compiled.len (
  count ++
  if count == compiled.len (
    out = out ++ compiled.[count]
  )
  if count != compiled.len (
    out = out ++ compiled.[count] ++ newline
  )
)
clipboard "set" out.destr
window "stop"
