current_tab_name = {"title":"Win Free Roblux!","icon":"image https://raw.githubusercontent.com/Mistium/Origin-OS/main/Websites/freerobux.web/assets/robux_icon.png 30"}

loc 2 -2 frame_width / 4 100
image "https://raw.githubusercontent.com/Mistium/Origin-OS/main/Websites/freerobux.web/assets/ROBUX.png" frame_width / 2.25

loc -2 -2 frame_width / -4 100
image "https://raw.githubusercontent.com/Mistium/Origin-OS/main/Websites/freerobux.web/assets/ROBUX.png" frame_width / 2.25

loc 999 999 0 frame_height / -1.5
image "https://raw.githubusercontent.com/Mistium/Origin-OS/main/Websites/freerobux.web/assets/generate.png" frame_width / 4.5

loc 999 999 0 frame height / -1.25
input 400 60 freeRobuxUsername "Username" 10
