clicked_id = 0
window "x" 0
window "y" 30
windowfileloc = "Origin/(C) Users/" ++ username ++ "/Desktop"
mainloop:
movefileloc windowfileloc
include windowfileloc
window "dimensions" screensize_x + 40 screensize_y - 60
applications_count = 0
loop desktop.len (
  applications_count += 1
  file "open" "id" desktop.[applications_count]
  file "get" "X"
  data2 = data
  file "get" "Y"
  goto data2 data - 25
  file "render" 2 "interactable"
)
