// print "value"
// getinput

//after days of ravenous labor, i present: calcoolator

num1 = "number 1".ask.int

num2 = "number 2".ask.int

getinput "operation"
operation = return.str

if operation == "+" "num3 = num1 + num2"
if operation == "-" "num3 = num1 - num2"
if operation == "*" "num3 = num1 * num2"
if operation == "/" "num3 = num1 / num2"
if operation == "^" "num3 = num1 ^ num2"
  
print num3
