code = "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++."
memory = 30.newVector()
pointer = 1
input_buffer = ""
output_buffer = ""

count = 0
while count < code.len (
  count ++
  switch code[count] (
    case ">"
      pointer += 1
      break
    case "<"
      pointer -= 1
      break
    case "+"
      memory[pointer] += 1
      break
    case "-"
      memory[pointer] -= 1
      break
    case "."
      output_buffer += memory[pointer].chr()
      break
    case ","
      memory[pointer] = "Input a Character".ask().ord()
      break
    case "["
      if memory[pointer] == 0 (
        openLoops = 1
        while openLoops > 0 (
          count ++
          if code[count] == "[" "openLoops ++"
          if code[count] == "]" "openLoops --"
        )
      )
      break
    case "]"
      if memory[pointer] != 0 (
        openLoops = 1
        while openLoops > 0 (
          count --
          if code[count] == "[" "openLoops --"
          if code[count] == "]" "openLoops ++"
        )
      )
      break
  )
)

say output_buffer
window "stop"
