camx = 2200
camy = 3120
window "show"
mainloop:
if "w".pressed "camy -= 1"
if "a".pressed "camx -= 1"
if "s".pressed "camy += 1"
if "d".pressed "camx += 1"
goto 0 0
image "https://mts1.google.com/vt/x=" ++ camx ++ "&y=" ++ camy ++ "&z=13" 400
goto 400 0
image "https://mts1.google.com/vt/x=" ++ ( camx + 1 ) ++ "&y=" ++ camy ++ "&z=13" 400
goto -400 0
image "https://mts1.google.com/vt/x=" ++ ( camx - 1 ) ++ "&y=" ++ camy ++ "&z=13" 400
import "win-buttons"
