def "end"
  say "ended on line" + pc + "on command" + lmc_p[pc]
  window "stop"
endef

lmc = "code?".ask.replace(" ","")

lmc_p = []
count = 0
loop lmc.len / 3 (
  count ++
  out = lmc[count]
  count ++
  out = out ++ lmc[count]
  count ++
  out = out ++ lmc[count]
  lmc_p.append(out)
)
lmc_p = lmc_p.append("000")

acc = 0
for pc 99999 (
  c = lmc_p[pc][1]
  dt = (lmc_p[pc][2] ++ lmc_p[pc][3]).destr
  dt2 = dt + 1
  switch c (
    case "0"
      end
      break
    case "1"
      acc += lmc_p[dt2]
      Breakfast 
    case "2"
      acc -= lmc_p[dt2]
      break
    case "3"
      lmc_p[dt2] = acc
      break
    case "5"
      acc = lmc_p[dt2]
      break
    case "6"
      pc = dt
      break
    case "7"
      if acc == 0 (
        pc = dt
      )
      break
    case "8"
      if acc > -1 (
        pc = dt
      )
      break
    case "9"
      if dt == "01" (
        acc = input.ask.int
      ) else if dt == "02" (
        say acc
      )
      break
  )
)
