lmc_code = "Enter the lmc code to run".ask

lmc_split = lmc_code.len.divide(3).round.new("array")

pc = 0
pc2 = -2
pc3 = 0
loop lmc_code (
  pc += 1
  pc2 += 3
  pc3 += 3
  lmc_split.[pc] = lmc_code.trim(pc2,pc3)
)


accumulator = 0

def "get" "id"
  command = id * 3
  command2 = command - 2
  data = lmc_code.trim(command2,command)
endef

pc = 0
loop lmc_code.len / 3 (
  pc += 1
  get pc
  input = data.trim(2,3)
  command = data.[1]
  if command == 1 "accumulator += input"
  
  if command == 5 "get input"
  if command == 5 "accumulator += data.trim(2,3)"
  
  if command == 9 and ( input == 2 ) "say accumulator"
)
