permission "request" "terminal"
network "set_app_id" "linker_handler"
window "responsive" true
linked_to = "Mist"
mainloop:
terminal "-get.windows"
windows = windows-names
terminal "get windowpositions"
if data.contains("-1,0") (
  id = data.index("-1,0")
  send_data = {}
  send_data.key("name") = windows.[id]
  send_data.key("side") = data.[id]
  network "send" send_data linked_to
  terminal "system windows close" + windows.[id]
)
