if terminal.stdin != null (
  void terminal.stdin.split("\n").map(v -> (
    terminal.writeLine(v)
  ))
) else if args.len > 0 (
  local dir = terminal.resolvePath(args[1])
  file "exists" dir
  if exists (
    void open(dir).split("\n").map(v -> (
      terminal.writeLine(v)
    ))
  ) else (
    terminal.writeLine("Unknown target file: " ++ args[1])
  )
) else (
  terminal.writeLine("cat: missing file operand")
)