// cd [dir]   change directory. Supports ~, /, .., relative paths and "-" (previous dir)
local target = "~"
local verbose = false
for i args.len (
  if args[i] == "-v" (
    verbose = true
  ) else (
    target = "" ++ args[i]
  )
)
if target == "-" (
  if terminal.oldpwd == null (
    terminal.writeLine("cd: OLDPWD not set")
    return
  )
  target = terminal.oldpwd
  verbose = true
)
local path = terminal.resolvePath(target)
if path != "origin" (
  file "exists" (path ++ ".folder")
  if !exists (
    file "exists" path
    if exists (
      terminal.writeLine("cd: not a directory: " ++ target)
    ) else (
      terminal.writeLine("cd: no such file or directory: " ++ target)
    )
    return
  )
)
terminal.oldpwd = terminal.pwd
terminal.pwd = path == "origin" ? "origin" ("origin" ++ path)
if verbose (
  terminal.writeLine(terminal.pwd)
)
