number used_size = user.used_size.toNum()
number max_size = user.max_size.toNum()

terminal.writeLine("Used        |   " ++ formatFileSize(used_size))
terminal.writeLine("Total       |   " ++ formatFileSize(max_size))
terminal.writeLine("Capacity    |   " ++ floor(used_size / max_size * 100) ++ "%")
terminal.writeLine("Files       |   " ++ "window.origin?.files?.index?.value?.length".eval() ?? "Unknown")