// history [n] | history -c
local numLines = null
for i args.len (
  if args[i] == "-c" (
    file "exists" "~/:path/history.txt"
    if exists (
      file "open" "~/:path/history.txt" "onlyaccess"
      file "set" 4 ""
      file "close"
    )
    last = []
    terminal.writeLine("history cleared")
    return
  ) else if args[i].toNum() != null (
    numLines = args[i].toNum()
  )
)

file "exists" "~/:path/history.txt"
if !exists (
  return
)
file "open" "~/:path/history.txt" "onlyaccess"
local history = fileGet(4).split("\n").filter(v -> v.len > 0)
file "close"

local start = 1
if numLines != null (
  start = max(1, (history.len - numLines) + 1)
)
for i history.len (
  if i >= start (
    terminal.writeLine(("" ++ i).padStart(" ", 5) ++ "  " ++ history[i])
  )
)
