local wins = "origin.windows".eval()
switch args[1] (
  case "-h"
    terminal.writeLine("htop [-h] [-l] [-g <window id>] [-r]")
    return
  case "-l"
    terminal.writeLine(wins.names.len)
    return
  case "-g"
    terminal.writeLine("window.osl_get_windows()".eval()[args[2]].JsonStringify())
    return
  case "-r"
    terminal.writeLine("window.osl_get_windows()".eval().JsonParse())
    return
  default
    terminal.writeLine("htop: invalid argument, use -h for help")
    return
)