// md5sum [file ...]   (stdin when no file)
if args.len == 0 (
  if terminal.stdin == null (
    terminal.writeLine("usage: md5sum [file ...]")
    return
  )
  terminal.writeLine(("" ++ terminal.stdin).hashMD5() ++ "  -")
  return
)
for i args.len (
  local p = terminal.resolvePath(args[i])
  file "exists" p
  if exists (
    terminal.writeLine(("" ++ open(p)).hashMD5() ++ "  " ++ args[i])
  ) else (
    terminal.writeLine("md5sum: " ++ args[i] ++ ": No such file or directory")
  )
)
