// rmdir dir ...   remove empty directories
if args.len == 0 (
  terminal.writeLine("usage: rmdir directory ...")
  return
)
for i args.len (
  local t = "" ++ args[i]
  local p = terminal.resolvePath(t)
  file "exists" (p ++ ".folder")
  if !exists (
    terminal.writeLine("rmdir: failed to remove '" ++ t ++ "': No such file or directory")
  ) else if listFiles(p).len > 0 (
    terminal.writeLine("rmdir: failed to remove '" ++ t ++ "': Directory not empty")
  ) else (
    file "open" (p ++ ".folder") "onlyaccess"
    file "delete"
  )
)
