// sha256sum [file ...]   (stdin when no file)
if args.len == 0 (
  if terminal.stdin == null (
    terminal.writeLine("usage: sha256sum [file ...]")
    return
  )
  terminal.writeLine(("" ++ terminal.stdin).hashSHA256() ++ "  -")
  return
)
for i args.len (
  local p = terminal.resolvePath(args[i])
  file "exists" p
  if exists (
    terminal.writeLine(("" ++ open(p)).hashSHA256() ++ "  " ++ args[i])
  ) else (
    terminal.writeLine("sha256sum: " ++ args[i] ++ ": No such file or directory")
  )
)
