// tac [file]   print lines in reverse order
local input = terminal.stdin
if input == null and args.len > 0 (
  local p = terminal.resolvePath(args[1])
  file "exists" p
  if !exists (
    terminal.writeLine("tac: " ++ args[1] ++ ": No such file or directory")
    return
  )
  input = "" ++ open(p)
)
if input == null (
  terminal.writeLine("usage: tac [file]")
  return
)
local lines = input.split("\n").reverse()
for i lines.len (
  terminal.writeLine(lines[i])
)
