window "show"
total = 300
list = []
loop total (
  rand = [0,100].random / 100
  list = list.append(rand)
)
sound "instrument" 20
current = 1
cycles = 0
mainloop:
w = window_width / total
c #fff
pen "size" 3
goto 0 -25
graph window_width window_height - 50 list
current ++
if current > ( total - cycles ) (
  current = 1
  cycles ++
)
c1 = current + 1
if list.[current] > list.[c1] (
  list = list.swap(current,c1)
)
sound "note" list.[current]
pen "up"
import "win-buttons"
