network "set_app_id" "mouse_syncer"
window "dimensions" screensize_x screensize_y
linked_to = "throwaway"
window "show"
last = timer
mainloop:
if new_network_data (
  if network_data_from == linked_to (
    mouse = network_data
  )
  new_network_data = false
)
goto mouse
image "https://static-00.iconduck.com/assets.00/mouse-cursor-icon-2048x2048-4tptourf.png" 40
if timer - last > 0.05 (
last = timer
network "send" [] + mouse_x + mouse_y linked_to
)

