network "set_app_id" "mouse_sync"
network "get_online"
online = network_data
pos = "array".new(99)
window "show"
mainloop:
if new_network_data (
item = online.index(network_data_from)
pos.[item] = network_data
new_network_data = false
)

count = 0
c #fff
loop online.len (
count ++
goto pos.[count].[1] pos.[count].[2]
square 1 1 10
)

if timer - last > 0.2 (
last = timer
count = 0
loop online.len (
count ++
network "send" [] + mouse_x + mouse_y online.[count]
)
)
import "win-buttons"
