loc 2 2 100 -50
c #333
input 160 30 "square" 

loc 2 2 20 -80
c #fff
i = 1
loop inputs.square (
  text inputs.square 10
)
i += 1
loop inputs.square - 2 (
  loc 2 2 20 -80 - ( i * 20 )
  text inputs.square 10
  loop inputs.square - 2 * inputs.square.len (
    text "*" 10
  )
  text inputs.square 10
  i += 1
)
loc 2 2 20 -80 - ( i * 20 )
loop inputs.square (
  text inputs.square 10
)
import "win-buttons"
