cam_pos = [
  0,
  0,
  0
]
cam_rotation = [
  0,
  0,
  0
]

file_dat = "obj".ask

render = file_dat.replace("  "," ").split(newline)
count = 0
loop render.len (
  count ++
  render.[count] = render.[count].split(" ")
)
say render

speed = 4
mainloop:
if "w".pressed (
  cam_pos.[1] += cam_rotation.[1].sin * speed
  cam_pos.[3] += cam_rotation.[1].cos * speed
)
if "s".pressed (
  cam_pos.[1] -= cam_rotation.[1].sin * speed
  cam_pos.[3] -= cam_rotation.[1].cos * speed
)
if "d".pressed (
  cam_pos.[1] += cam_rotation.[1].add(90).sin * speed
  cam_pos.[3] += cam_rotation.[1].add(90).cos * speed
)
if "a".pressed (
  cam_pos.[1] -= cam_rotation.[1].add(90).sin * speed
  cam_pos.[3] -= cam_rotation.[1].add(90).cos * speed
)
if "left arrow".pressed (
  cam_rotation.[1] -= 5
)
if "right arrow".pressed (
  cam_rotation.[1] += 5
)
if "up arrow".pressed (
  cam_rotation.[2] += 5
)
if "down arrow".pressed (
  cam_rotation.[2] -= 5
)
3d "camera" "position" cam_pos
3d "camera" "rotation" cam_rotation
loc 2 2 20 -20
text cam_pos 10 : c#fff
loc 2 2 20 -40
text cam_rotation 10
c #fff
count = 0
loop render.len (
  count ++
  current = render.[count]
  if current.[1] == "f" (
    pos1 = current.[2]
    pos1 = render.[pos1].delete(1).vproject("camera")
    pos2 = current.[3]
    pos2 = render.[pos2].delete(1).vproject("camera")
    pos3 = current.[4]
    pos3 = render.[pos3].delete(1).vproject("camera")
    goto 0 0
    triangle pos1.[1] pos1.[2] pos2.[1] pos2.[2] pos3.[1] pos3.[2]
  )
)

import "win-buttons"
