cam_pos = [0,0,0]
cam_rotation = [0,0,0]

def "render_tri" "p1,p2,p3"
  goto 0 0
  p1.vproject("camera")
  p2.vproject("camera")
  p3.vproject("camera")
  triangle p1.[1] p1.[2] p2.[1] p2.[2] p3.[1] p3.y[2]
endef

speed = 4
mainloop:
if "w".pressed (
  cam_pos.[1] += cam_rotation.[1].sin * speed
  cam_pos.[3] += cam_rotation.[1].cos * speed
)
if "s".pressed (
  cam_pos.[1] -= cam_rotation.[1].sin * speed
  cam_pos.[3] -= cam_rotation.[1].cos * speed
)
if "d".pressed (
  cam_pos.[1] += cam_rotation.[1].add(90).sin * speed
  cam_pos.[3] += cam_rotation.[1].add(90).cos * speed
)
if "a".pressed (
  cam_pos.[1] -= cam_rotation.[1].add(90).sin * speed
  cam_pos.[3] -= cam_rotation.[1].add(90).cos * speed
)
if "left arrow".pressed (
  cam_rotation.[1] -= 5
)
if "right arrow".pressed (
  cam_rotation.[1] += 5
)
if "up arrow".pressed (
  cam_rotation.[2] += 5
)
if "down arrow".pressed (
  cam_rotation.[2] -= 5
)
3d "camera" "position" cam_pos
3d "camera" "rotation" cam_rotation
loc 2 2 20 -20
text cam_pos 10 : c#fff
loc 2 2 20 -40
text cam_rotation 10
c #f00
render_tri [-100,100,0] [100,100,0] [0,0,0]
c #00f
render_tri [100,100,0] [100,-100,0] [0,0,0]
c #0f0
render_tri [100,-100,0] [-100,100,0] [-100,-100,0]
loc 2 2 20 -60
text fps.str + "fps" 10 : c#fff
import "win-buttons"
