cam_pos = [
  0,
  0,
  0
]
cam_rotation = [
  0,
  0,
  0
]

file = "
# OBJ file created by ply_to_obj.c
#
g Object001

v  0  0  0
v  1  0  0
v  1  1  0
v  0  1  0
v  0.5  0.5  1.6

f  5  2  3
f  4  5  3
f  6  3  2
f  5  6  2
f  4  6  5
f  6  4  3
"
  
speed = 4
mainloop:
if "w".pressed (
  cam_pos.[1] += cam_rotation.[1].sin * speed
  cam_pos.[3] += cam_rotation.[1].cos * speed
)
if "s".pressed (
  cam_pos.[1] -= cam_rotation.[1].sin * speed
  cam_pos.[3] -= cam_rotation.[1].cos * speed
)
if "d".pressed (
  cam_pos.[1] += cam_rotation.[1].add(90).sin * speed
  cam_pos.[3] += cam_rotation.[1].add(90).cos * speed
)
if "a".pressed (
  cam_pos.[1] -= cam_rotation.[1].add(90).sin * speed
  cam_pos.[3] -= cam_rotation.[1].add(90).cos * speed
)
if "left arrow".pressed (
  cam_rotation.[1] -= 5
)
if "right arrow".pressed (
  cam_rotation.[1] += 5
)
if "up arrow".pressed (
  cam_rotation.[2] += 5
)
if "down arrow".pressed (
  cam_rotation.[2] -= 5
)
3d "camera" "position" cam_pos
3d "camera" "rotation" cam_rotation
loc 2 2 20 -20
text cam_pos 10 : c#fff
loc 2 2 20 -40
text cam_rotation 10
goto [100,50,100].vproject("camera")
c #fff
pen "size" 3
pen "down"
goto [100,-50,100].vproject("camera")
goto [100,-50,-100].vproject("camera")
pen "up"
import "win-buttons"
