window "show"
import "win-buttons"
// TODO: Move import to mainloop (?)
window "dimensions" 300 600
window "resizable" false
// changed this cos docs were wrong, needs to have false as a bool not as a string

rating = ""
drank = 0
percent = 0
// setup tingz ^

mainloop:
drank += 1
// TODO: delete this ^

goal = 125
// sets the goal ^

low = goal / 3
mid = low * 2
// sets the 3 stages you can be in ^

if drank < low (
rating = "frowney"
)
if drank > low and drank < mid (
rating = "neutraley"
)
if drank > mid and drank < goal (
rating = "smiley"
)

percent = drank * ( 100 / goal )
display = percent.round
// calculates a percent, and rounds it to a displayable number ^

c #fff
goto 0 140
change_x display.len + 1 * -10
text "<display>%" 20
// shows the percent to the user ^

goto 0 140
fill = display * 1.8
dir = display / 5.55
// makes the ring fill out correctly ^

icon "w 2 c #fff cutcircle 0 0 10 0 180" 10
icon "w 1.5 c #6488ea cutcircle 0 0 10" + dir + fill 10
// draws the ring ^

info = "<drank>oz of <goal>oz"
goto info.len * -4 0
// moved the change_x into the goto

text info 12
