window "show"
import "win-buttons"
// TODO: Move import to mainloop (?)
window "dimensions" 300 600
window "resizable" false
// changed this cos docs were wrong, needs to have false as a bool not as a string

rating = ""
drank = 0
percent = 0
// setup tingz ^

mainloop:
drank += 1
// TODO: delete this ^

goal = 125
// sets the goal ^

low = goal / 3
mid = goal * 2 / 3
// sets the 3 stages you can be in ^

rating = "w 1.5 cutcircle 0 0 10 0 180 dot 3 3 dot -3 3 cutcircle 0 0 5 90 90"
// smile

if drank < low (
  rating = "w 1.5 cutcircle 0 0 10 0 180 dot 3 3 dot -3 3 cutcircle 0 -5.5 5 0 80"
  // frown
) else (
  if drank < mid (
    rating = "w 1.5 cutcircle 0 0 10 0 180 dot 3 2 dot -3 2 line -4 -2 4 -2"
    // meh
  )
)

percent = drank * ( 100 / goal )
display = percent.round
// calculates a percent, and rounds it to a displayable number ^

c #fff
goto 0 155
icon rating.str 2
goto 0 105
change_x display.len + 1 * -7.7
text "<display>%" 17
// shows the percent to the user ^

goto 0 140
fill = display * 1.8
dir = display / 5.55
// makes the ring fill out correctly ^

icon "w 2 c #fff cutcircle 0 0 10 0 180" 10
icon "w 1.5 c #6488ea cutcircle 0 0 10" + dir + fill 10
// draws the ring ^

info = "<drank>oz of <goal>oz"
goto info.len * -4 0

text info 12
goto -100 -140
text "<low.round>, <mid.round>, <goal.round>" 10
