code = "input bc code here".ask

code = code.regex("/(?<=\()[^)]+(?=\))|[^ \n()%;]+|[()]|%[^%]*%|;/gm")
loop code.len (
  count += 1
  cur = code.[count]
  last = cur.len
  if cur.[1] == "%" and ( cur.[last] == "%" ) (
    cur = ""
  )
)

window "show"

console = [] + "> Successfully loaded console (v0.1)".destr
console = console + "> fixed the bug and i have more lines".destr

mainloop:

c #fff
loc 2 2 20 -20
text "BetterCode Console" 10

loc 2 2 20 -40
text console.join(newline) 10

import "win-buttons"
