console = [] + "> Successfully loaded console (v0.1)".destr
console = console + "> fixed the bug and i have more lines".destr

code = "input bc code here".ask

splitter = "/\'[^\']+\'|(?<=\()[^)]+(?=\))|[^ \n()%;]+|[()]|%[^%]*%|;/gm"

code = code.regex(splitter)
loop code.len (
  pass = ""
  count += 1
  cur = code.[count]
  last = cur.len

  count2 = count + 1
  next = code.[count2]
  count2 += 1
  next2 = code.[count2]

  if cur.[1] == "%" and ( cur.[last] == "%" ) (
    cur = ""
  )
  if cur === "console".destr and ( next == "(" ) (
    pass = "say" + next2.str
    pass = pass.destr
  )
  if pass != "" (
    console = console + pass
  )
)

window "show"

mainloop:

c #fff
loc 2 2 20 -20
text "BetterCode Console" 10

loc 2 2 20 -40
text console.join(newline) 10

import "win-buttons"
