if onload (
current_tab_name = "Summit Web Store"
store_data = "owtp:/summit.web/store/extensions.json".get()
store_keys = store_data.getall("keys")
store_values = store_data.getall("values")
)

for count in store_data (
y = count * -40 - 50
c #222
loc 999 2 -20 y
square frame_width - 70 30 10 1
loc -2 2 -30 y
square 30 30 10 1
c #fff
loc 2 2 20 y
text store_keys.[count] 8
loc -2 2 -30 y
icon "download" 0.8
)
