
width = 214

def conditions() (
  return false
)

def main() (
  change_x 107
  set_y y
  change_x -84
  file "open" "~/Downloads.folder" "onlyaccess"
  file "render" 2.1
  if onclick (
    file "start"
  )
  change_x 56
  file "open" "~/Documents.folder" "onlyaccess"
  file "render" 2.1
  if onclick (
    file "start"
  )
  change_x 56
  file "open" "~/Applications.folder" "onlyaccess"
  file "render" 2.1
  if onclick (
    file "start"
  )
  change_x 56
  file "open" "~/Bin.folder" "onlyaccess"
  file "render" 2.1
  if onclick (
    file "start"
  )
)