window "resizable" False
window "show"
canclick = False
operation = ""
current = null
secondary = null

def "draw" "x, y, x2, y2, character"
  loc x y x2 + 5 y2 + 65
  if operation.str == character (
    square 55 55 10 : c#co hover_c#coh
  ) else (
    square 55 55 10 : c#cb hover_c#cbh
  )

  character.destr
  if can and (character.istype("number") or character == ".") (
    if clicked or character.onpress (
      can = false
      if operation == "" (
        c = current
        current = current ++ character
      ) else (
        s = secondary
        secondary = secondary ++ character
      )
    )
  )
  if clicked or character.onpress and "+-x÷".contains(character) "operation = character.str"
  if clicked or "enter".pressed and ( character.str == "=" ) (
    current.int
    secondary.int
    if operation == "+" "current += secondary"
    if operation == "-" "current -= secondary"
    if operation == "x" "current *= secondary"
    if operation == "÷" "current /= secondary"
    current.str
    secondary = 0
    operation = ""
  )
  change -10 -5
  text character.str 20 : c#ct
endef

co = #f79204
coh = #f7ae43

window "show"
window "dimensions" 280 380
window "resizable" false

mainloop:

theme = user.theme
cb = theme.primary
cbh = theme.secondary
cca = theme.primary
ctb = theme.primary
ct = theme.text
rh = theme.tertiary
window_colour = theme.background


loc 999 2 0 -22.5
square 265 30 10 1 : c#ctb

loc 999 2 0 -72.5
square 265 40 10 : c#cca

loc 2 2 20 -22.5
text "Calculator" 9 : c#ct

draw 2 2 30 -200 "1"
draw 2 2 100 -200 "2"
draw 2 2 170 -200 "3"
draw 2 2 240 -200 "+"

draw 2 2 30 -270 "4"
draw 2 2 100 -270 "5"
draw 2 2 170 -270 "6"
draw 2 2 240 -270 "-"

draw 2 2 30 -340 "7"
draw 2 2 100 -340 "8"
draw 2 2 170 -340 "9"
draw 2 2 240 -340 "x"

draw 2 2 30 -410 "."
draw 2 2 100 -410 "0"
draw 2 2 170 -410 "="
draw 2 2 240 -410 "÷"

loc 2 2 25 -72.5
if operation == "" "output = current" else "output = secondary"
if output == null "output = 0"
text output 15

loc -2 2 -27.5 -72.5
square 40 40 10 : c#cca hover_c#ch
icon "left-arrow" 0.7 : c#ct
if clicked or "backspace".pressed and can (
  can = false
  temp = current.len - 1
  temp2 = secondary.len - 1
  if operation == "" "current.left(temp)" else "secondary.left(temp2)"
)

loc -2 2 -22.5 -22.5
icon "close" 0.6
if clicked "window stop"
if mouse_down.not "can = True"
