buttons = [
  "GET","POST","PUT","PATCH",
  "DELETE","HEAD","OPTIONS"
]

// variable setup
response = ""
response_code = "-"
resp_all = ""
resp = ""
resp_len = 0
http "new"
response_failed = false
response_success = false
last_response_failed = false
last_response_success = false
window "set_dragbox" [[2,2,0,0],[-2,2,-40,-40]]
inputs.Url = ""
inputs.body = ""
inputs.type = "text/plain"
selected = 1

// shows the window
window "show"


mainloop:
loc 2 2 15 -20
text "HTTP Client" 9 : c#fff

// draws the method buttons
loc 2 2 40 -55
for "count" buttons.len (
  c #222
  // highlights the selected button
  if selected == count "c #444"
  square 60 20 10
  if onclick (
    // switches the selected button
    selected = count
  )
  c #fff
  x = x_position
  change_x -30
  text buttons[count] 8
  set_x x + 75
)

loc 2 2 10 -90
text "Make a " ++ buttons[selected] ++ " request to a website:" 10 : c#fff
loc 2 2 window.width - 50 -130
send_clicked = mouse_ondown and abs(mouse_press_x - x_position) < 45 and abs(mouse_press_y - y_position) < 18
square 80 25 10 : c#333 hover_c#444 click_c#222
if send_clicked (
  // send the HTTP request when Send is activated
  response_code = "pending"
  last_response_failed = false
  last_response_success = false
  http "new"
  http "method" buttons[selected]
  http "body" inputs.body
  http "type" inputs.type
  http "sendto" inputs.Url
)
c #fff
change_x -20
text "Send" 10

loc 2 2 0 -130
set_x -50
c #333
w = window_width - 120
square w 25 10
input w - 10 25 "Url" "Enter url of website to request"

// render the request body input
loc 99999 2 0 -170
square window_width - 20 25 10 : c#333
if buttons[selected] == "get" (
  loc 2 2 15 -170
  text "Can't use a request body for GET" 8 : c#fff
) else (
  input window_width - 30 25 "body" "Request body"
)

// render the request type input
loc 99999 2 0 -210
square window_width - 20 25 10 : c#333
input window_width - 30 25 "type" "text/plain"

if response_failed or response_success (
  // get the response and then handle it
  http "get_response"
  last_response_failed = response_failed
  last_response_success = response_success
  resp_all = response
  resp_len = resp_all.len
  resp = response.split(newline)[1].trim(1,100)
  http "new"
)
loc 2 2 10 -250
c #fff
text "Received a response, code: " ++ (response_code ?? "-") 10
change_x 30
// draws whether the request succeeded lol
if last_response_success (
  text "Response Succeeded" 10
)
if last_response_failed (
  text "Response Failed" 10
)

// render the response data
loc 2 2 10 -280
text "Received: " ++ resp_len ++ " text characters" 10
loc 2 2 10 -330
text resp 10

// position the copy button
loc 2 2 140 -380
c #333
copy_clicked = mouse_ondown and abs(mouse_press_x - x_position) < 130 and abs(mouse_press_y - y_position) < 18
button "Copy response to clipboard" 250 25 10 : hover_c#444 click_c#222
if copy_clicked (
  clipboard "set" resp_all.toStr().destr
)

import "win-buttons"
