can = false
timetemp = null
mainloop:
window "dimensions" screensize_x screensize_y
if mouse_down (
  if can (
    can = "exit"
  )
) else (
  if can == "exit" (
    window "stop"
  )
  can = true
)
square window_width window_height 10 : c#000
time = hour ++ ":" ++ minute ++ ":" ++ second
goto time.len * -20 0
c #aaa
text time 40
exit_txt = "Click to exit"
goto exit_txt.len * -5 -100
c #777
text exit_txt 10
