network "get" "https://api.github.com/repos/Mistium/Origin-OS/git/trees/main?recursive=1"
index = data.key("tree")
data = null
len = index.len
r = ["1"].append(len)
item = r.random
if [1,100].random == 1 and index.[item].key("path").contains("Websites/") (
redirect index.[item].key("path").replace("Websites/","owtp://")
)
if index.[item].key("path").contains("Websites/") (
loc 2 2 20 -20
text index.[item].key("path") 10 : c#c_text
)
