seticon ""
cookies = 0
window "show"
last_upgrade_cookies = 0
cursor_per = 0.1
grandma_per = 1

costs = [15,100,1100,12000,130000,1400000]
upgrades = [0,0,0,0,0,0]

def "button" "url,upgrade,item,size"
x = x_position
y = y_position
square 200 30 20 0 1
c #111
if cookies.ceiling >= costs.[item].ceiling (
c #222
if mouse_touching (
c #333
change_x -5
x -= 5
if clicked and can (
last_upgrade_cookies -= costs.[item].floor
last_upgrade = timer
can = false
upgrades.[item] += 1
costs.[item] *= 1.15
)
)
)
square 200 30 20
change_x -85
image url size
change 30 -10
image cookie_url 20
text costs.[item].floor 9 : c#fff chx#15
goto x - 65 y + 10
text upgrade 9
goto x + 65 y
text upgrades.[item] 10 : c#aaa
endef

cookie_url = "https://raw.githubusercontent.com/Mistium/Origin-OS/main/3rd%20Party/3rdPartyDevs/RattusDong/Cookie/PerfectCookie.png"

cursor = "https://raw.githubusercontent.com/Mistium/Origin-OS/main/3rd%20Party/3rdPartyDevs/RattusDong/Cookie/Cursor_64px.png"
grandma = "https://static.wikia.nocookie.net/cookieclicker/images/a/a0/GrandmaIconTransparent.png"
mainloop:

loc -2 2 -20 -20
square 20 20 20 : c#222
icon "close" 0.8 : c#DECBB7
if clicked "window stop"

t = timer * 150
width += target - width / 5
loc 2 2 200 -240
image cookie_url width
target = 200
if mouse_touching (
  if mouse_down (
    if can (
      last_upgrade_cookies += 1
      can = false
    )
    target = 200
  ) else (
    target = 250
  )
) else (
  target = 180
)
cps = ( upgrades.[1] * cursor_per ) + ( upgrades.[2] * grandma_per ) * 10
cps = round(cps) / 10
cps_displ = "per second:" + cps

if mouse_down.not "can = true"
cookies_displ = cookies.floor + "Cookies"
loc 2 2 200 + ( cookies_displ.len * -7 ) -50
text cookies_displ 14 : c#fff
loc 2 2 200 + ( cps_displ.len * -5 ) -70
text cps_displ 10

cookies = last_upgrade_cookies + ( timer - last_upgrade * cps )
if cookies < 0 (
cookies = 0
last_upgrade_cookies = 0
)

loc -2 2 -100 -80
direction 110
button cursor "Cursor" 1 100
direction 90
loc -2 2 -100 -135
button grandma "Grandma" 2 40
